spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: category-service
              uri: lb://CATEGORY-SERVICE
              predicates:
                - Path=/api/category/**
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**
            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/api/product/**
            - id: supplier-service
              uri: lb://SUPPLIER-SERVICE
              predicates:
                - Path=/api/supplier/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      access: unrestricted
jwt:
  secret: "5367566859703373367639792F423F452848284D6251655468576D5A71347437"